%{
    #include <stdio.h>
%}

%token INT CHAR IF ELSE ELSEIF WHILE FOR RETURN VOID MAIN CONTINUE BREAK IDENTIFIER INT_CONST OUT_OF_RANGE
ONE_LINE_COMMENT MULTI_LINE_COMMENT LESS_EQUAL EQUAL NOT_EQUAL GREATER_EQUAL BITWISE_OR BITWISE_AND OR AND 
BITWISE_XOR NOT PLUS MINUS DIVISION MULTIPLY ASSIGN LEFTPAREN RIGHTPAREN LEFTBRACKET RIGHTBRACKET LEFTB
RIGHTB COMMA DOT MYSTERY

%start input

%%


%%